### ISSUE TITLE
Request for permission to share your great CSU materials

### ISSUE THREAD

**Issue by FeijiangHan** [LukiRyan/CSU-CS_DS-Assignments#1]
Hey there,

I came across your GitHub repository and I'm really impressed with the work you've done. 

I'm currently putting together a larger collection of study resources for CSU students. Would you be open to me including a link to your repo in the README of my collection? I think sharing quality resources like yours could really help other students.

My goal is to build an extensive guide with multiple tools and materials in one place. Linking to your repo would help more people discover the valuable information you've organized. Of course, I would properly attribute the source.

Please let me know if this is okay with you. I appreciate any help in making comprehensive study tools available. Thanks for considering!

**Comment by LukiRyan** [comment]
It's my great honor. We used to be in Ms. Luo's Simulated Electronic Technology class together😂. I never thought that to get to konw you in this way. May I add you as QQfriend?

**Comment by LukiRyan** [comment]
Of course, it would be my great honor to be a part of your sharing.
